//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace Novell.Directory.Ldap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novell.Directory.Ldap.Properties.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot bind. Use PoolManager.getBoundConnection().
        /// </summary>
        internal static string CANNOT_BIND {
            get {
                return ResourceManager.GetString("CANNOT_BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed by the application disconnecting.
        /// </summary>
        internal static string CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server {0}:{1}.
        /// </summary>
        internal static string CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed by the application finalizing the object.
        /// </summary>
        internal static string CONNECTION_FINALIZED {
            get {
                return ResourceManager.GetString("CONNECTION_FINALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reconnect to server, application has never called connect().
        /// </summary>
        internal static string CONNECTION_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("CONNECTION_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader thread terminated.
        /// </summary>
        internal static string CONNECTION_READER {
            get {
                return ResourceManager.GetString("CONNECTION_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost waiting for results from {0}:{1}.
        /// </summary>
        internal static string CONNECTION_WAIT {
            get {
                return ResourceManager.GetString("CONNECTION_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Decoding responseValue.
        /// </summary>
        internal static string DECODING_ERROR {
            get {
                return ResourceManager.GetString("DECODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DN parameter.
        /// </summary>
        internal static string DN_PARAM_ERROR {
            get {
                return ResourceManager.GetString("DN_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcLdapMessage: Cannot duplicate message built from the input stream.
        /// </summary>
        internal static string DUP_ERROR {
            get {
                return ResourceManager.GetString("DUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Error.
        /// </summary>
        internal static string ENCODING_ERROR {
            get {
                return ResourceManager.GetString("ENCODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry parameter.
        /// </summary>
        internal static string ENTRY_PARAM_ERROR {
            get {
                return ResourceManager.GetString("ENTRY_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting left parenthesis, found &quot;{0}&quot;.
        /// </summary>
        internal static string EXPECTING_LEFT_PAREN {
            get {
                return ResourceManager.GetString("EXPECTING_LEFT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting right parenthesis, found &quot;{0}&quot;.
        /// </summary>
        internal static string EXPECTING_RIGHT_PAREN {
            get {
                return ResourceManager.GetString("EXPECTING_RIGHT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Failed Referral: {1}.
        /// </summary>
        internal static string FAILED_REFERRAL {
            get {
                return ResourceManager.GetString("FAILED_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral not supported for command {0}.
        /// </summary>
        internal static string IMPROPER_REFERRAL {
            get {
                return ResourceManager.GetString("IMPROPER_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax for address with port; {0}.
        /// </summary>
        internal static string INVALID_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &quot;{0}&quot; in attribute description.
        /// </summary>
        internal static string INVALID_CHAR_IN_DESCR {
            get {
                return ResourceManager.GetString("INVALID_CHAR_IN_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid character &quot;{0}&quot; needs to be escaped as &quot;{1}&quot;.
        /// </summary>
        internal static string INVALID_CHAR_IN_FILTER {
            get {
                return ResourceManager.GetString("INVALID_CHAR_IN_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence not allowed in attribute description.
        /// </summary>
        internal static string INVALID_ESC_IN_DESCR {
            get {
                return ResourceManager.GetString("INVALID_ESC_IN_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in escape sequence &quot;{0}&quot;.
        /// </summary>
        internal static string INVALID_ESCAPE {
            get {
                return ResourceManager.GetString("INVALID_ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid comparison operator.
        /// </summary>
        internal static string INVALID_FILTER_COMPARISON {
            get {
                return ResourceManager.GetString("INVALID_FILTER_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Exception on host {0}, port {1}.
        /// </summary>
        internal static string IO_EXCEPTION {
            get {
                return ResourceManager.GetString("IO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Matched DN: {1}.
        /// </summary>
        internal static string MATCHED_DN {
            get {
                return ResourceManager.GetString("MATCHED_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched parentheses, left parenthesis missing.
        /// </summary>
        internal static string MISSING_LEFT_PAREN {
            get {
                return ResourceManager.GetString("MISSING_LEFT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched parentheses, right parenthesis missing.
        /// </summary>
        internal static string MISSING_RIGHT_PAREN {
            get {
                return ResourceManager.GetString("MISSING_RIGHT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple schema found when reading the subschemaSubentry for {0}.
        /// </summary>
        internal static string MULTIPLE_SCHEMA {
            get {
                return ResourceManager.GetString("MULTIPLE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing attribute description.
        /// </summary>
        internal static string NO_ATTRIBUTE_NAME {
            get {
                return ResourceManager.GetString("NO_ATTRIBUTE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN and matching rule not specified.
        /// </summary>
        internal static string NO_DN_NOR_MATCHING_RULE {
            get {
                return ResourceManager.GetString("NO_DN_NOR_MATCHING_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot duplicate message to follow referral for {0} request, not allowed.
        /// </summary>
        internal static string NO_DUP_REQUEST {
            get {
                return ResourceManager.GetString("NO_DUP_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing matching rule.
        /// </summary>
        internal static string NO_MATCHING_RULE {
            get {
                return ResourceManager.GetString("NO_MATCHING_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results could not be stored in memory, sort failed.
        /// </summary>
        internal static string NO_MEMORY {
            get {
                return ResourceManager.GetString("NO_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon present, but no option specified.
        /// </summary>
        internal static string NO_OPTION {
            get {
                return ResourceManager.GetString("NO_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schema found when reading the subschemaSubentry for {0}.
        /// </summary>
        internal static string NO_SCHEMA {
            get {
                return ResourceManager.GetString("NO_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to stopTLS on a connection where startTLS had not been called.
        /// </summary>
        internal static string NO_STARTTLS {
            get {
                return ResourceManager.GetString("NO_STARTTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested property is not supported..
        /// </summary>
        internal static string NO_SUP_PROPERTY {
            get {
                return ResourceManager.GetString("NO_SUP_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTLS failed because no LdapTLSSocketFactory has been set for this Connection.
        /// </summary>
        internal static string NO_TLS_FACTORY {
            get {
                return ResourceManager.GetString("NO_TLS_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema element is not an LdapAttributeSchema object.
        /// </summary>
        internal static string NOT_AN_ATTRIBUTE {
            get {
                return ResourceManager.GetString("NOT_AN_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method LdapConnection.startTLS not implemented.
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extended operation parameter, no OID specified.
        /// </summary>
        internal static string OP_PARAM_ERROR {
            get {
                return ResourceManager.GetString("OP_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start or stop TLS because outstanding Ldap operations exist on this connection.
        /// </summary>
        internal static string OUTSTANDING_OPERATIONS {
            get {
                return ResourceManager.GetString("OUTSTANDING_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        internal static string PARAM_ERROR {
            get {
                return ResourceManager.GetString("PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DN or RDN parameter.
        /// </summary>
        internal static string RDN_PARAM_ERROR {
            get {
                return ResourceManager.GetString("RDN_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read response is ambiguous, multiple entries returned.
        /// </summary>
        internal static string READ_MULTIPLE {
            get {
                return ResourceManager.GetString("READ_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to follow a search continuation reference.
        /// </summary>
        internal static string REFERENCE_ERROR {
            get {
                return ResourceManager.GetString("REFERENCE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result reference received, and referral following is off.
        /// </summary>
        internal static string REFERENCE_NOFOLLOW {
            get {
                return ResourceManager.GetString("REFERENCE_NOFOLLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapBind.bind() function returned null.
        /// </summary>
        internal static string REFERRAL_BIND {
            get {
                return ResourceManager.GetString("REFERRAL_BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not match LdapBind.bind() connection with Server Referral URL list.
        /// </summary>
        internal static string REFERRAL_BIND_MATCH {
            get {
                return ResourceManager.GetString("REFERRAL_BIND_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to follow a referral.
        /// </summary>
        internal static string REFERRAL_ERROR {
            get {
                return ResourceManager.GetString("REFERRAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Referral: {1}.
        /// </summary>
        internal static string REFERRAL_ITEM {
            get {
                return ResourceManager.GetString("REFERRAL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapSearchResults.{0}(): No entry found &amp; request is not complete.
        /// </summary>
        internal static string REFERRAL_LOCAL {
            get {
                return ResourceManager.GetString("REFERRAL_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending request to referred server.
        /// </summary>
        internal static string REFERRAL_SEND {
            get {
                return ResourceManager.GetString("REFERRAL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to server {0} while attempting to follow a referral.
        /// </summary>
        internal static string SERVER_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Server Message: {1}.
        /// </summary>
        internal static string SERVER_MSG {
            get {
                return ResourceManager.GetString("SERVER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unsolicited notification from server {0}:{1} to shutdown.
        /// </summary>
        internal static string SERVER_SHUTDOWN_REQ {
            get {
                return ResourceManager.GetString("SERVER_SHUTDOWN_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete escape sequence.
        /// </summary>
        internal static string SHORT_ESCAPE {
            get {
                return ResourceManager.GetString("SHORT_ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that SSL Provider is properly installed..
        /// </summary>
        internal static string SSL_PROVIDER_MISSING {
            get {
                return ResourceManager.GetString("SSL_PROVIDER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping TLS: Error getting input &amp; output streams from the original socket.
        /// </summary>
        internal static string STOPTLS_ERROR {
            get {
                return ResourceManager.GetString("STOPTLS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} ({2}) {3}.
        /// </summary>
        internal static string TOSTRING {
            get {
                return ResourceManager.GetString("TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of attribute Name array does not equal length of Flags array.
        /// </summary>
        internal static string UNEQUAL_LENGTHS {
            get {
                return ResourceManager.GetString("UNEQUAL_LENGTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of filter.
        /// </summary>
        internal static string UNEXPECTED_END {
            get {
                return ResourceManager.GetString("UNEXPECTED_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Ldap result code {0}.
        /// </summary>
        internal static string UNKNOWN_RESULT {
            get {
                return ResourceManager.GetString("UNKNOWN_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTLS cannot use the set socket factory because it does not implement LdapTLSSocketFactory.
        /// </summary>
        internal static string WRONG_FACTORY {
            get {
                return ResourceManager.GetString("WRONG_FACTORY", resourceCulture);
            }
        }
    }
}
